include: package:pedantic/analysis_options.1.9.0.yaml

linter:
  rules:
    - avoid_types_on_closure_parameters
    - close_sinks
    - prefer_const_literals_to_create_immutables
    - cancel_subscriptions
    - prefer_const_constructors
    - unnecessary_brace_in_string_interps
    - unnecessary_statements
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - use_string_buffers
    - use_is_even_rather_than_modulo
    - unnecessary_await_in_return
    - prefer_is_not_operator
    - constant_identifier_names
    - unnecessary_final

analyzer:
  exclude:
    - lib/features/domain/bloc/**/*.freezed.dart
    - lib/features/data/models/local/*.g.dart
    - lib/generated/**
    - lib/**.config.dart